# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: nvm install && nvm use && npm install # runs during prebuild
    command: git config --global user.email $GIT_COMMITTER_EMAIL && git config --global user.name $GIT_AUTHOR_NAME